### PR TITLE
(Different algorithms of linked list)

### PR DESCRIPTION
**Pull request by ShubhangiShrestha**

### CODE REVIEW

**Comment by Ashish-kumar7** [comment]
what is the actual idea ?

**Comment by ShubhangiShrestha** [comment]
I viewed many solutions to the problems, so I thought to put some basic algorithms of linked list there.
Are you asking anything else?

**Comment by Ashish-kumar7** [comment]
okay !
But this repo contains the code 
if you can write some relevant code i.e the code should not be present here already. I can look for it.
Thanks

**Comment by ShubhangiShrestha** [comment]
Written a code in C++ , which I've not found in this repo

**Review by Ashish-kumar7 — APPROVED** [review]

**Comment by ShubhangiShrestha** [comment]
Is my contribution is hacktoberfest acceptable? If so, can you please add Hacktoberfest-accepted lable to it?

**Pull request merged**
