### PR TITLE
added a linear search program using c++

### PR DESCRIPTION
**Pull request by aditi830**

### CODE REVIEW

**Comment by Ashish-kumar7** [comment]
Please star the repo and add a medium-level questions solution.
Thanks

**Comment by aditi830** [comment]
Sir, where can I find those medium level questions?

Sent from Yahoo Mail on Android 
 
  On Sat, 2 Oct 2021 at 12:43 am, Ashish ***@***.***> wrote:   


Please star the repo and add a medium-level questions solution.
Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ashish-kumar7** [comment]
https://practice.geeksforgeeks.org/problems/last-index-of-15847/1
add the solution of this question.
Thanks.

**Comment by aditi830** [comment]
Sir I have added solution of  problem last index of one.

Sent from Yahoo Mail on Android 
 
  On Sat, 2 Oct 2021 at 1:36 pm, Ashish ***@***.***> wrote:   


https://practice.geeksforgeeks.org/problems/last-index-of-15847/1
add the solution of this question.
Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
